# Generated by Django 4.2 on 2025-08-18 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("completed_responses", models.PositiveIntegerField(default=0)),
                ("abandoned_responses", models.PositiveIntegerField(default=0)),
                ("average_completion_time", models.FloatField(default=0)),
                ("median_completion_time", models.FloatField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("return_visitors", models.PositiveIntegerField(default=0)),
                ("desktop_responses", models.PositiveIntegerField(default=0)),
                ("mobile_responses", models.PositiveIntegerField(default=0)),
                ("tablet_responses", models.PositiveIntegerField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("include_metadata", models.BooleanField(default=True)),
                ("anonymize_responses", models.BooleanField(default=False)),
                ("date_range_start", models.DateTimeField(blank=True, null=True)),
                ("date_range_end", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("skipped_responses", models.PositiveIntegerField(default=0)),
                ("option_counts", models.JSONField(default=dict)),
                ("average_rating", models.FloatField(default=0)),
                ("rating_distribution", models.JSONField(default=dict)),
                ("average_text_length", models.FloatField(default=0)),
                ("common_words", models.JSONField(default=list)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_surveys", models.PositiveIntegerField(default=0)),
                ("active_surveys", models.PositiveIntegerField(default=0)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("responses_today", models.PositiveIntegerField(default=0)),
                ("responses_this_week", models.PositiveIntegerField(default=0)),
                ("responses_this_month", models.PositiveIntegerField(default=0)),
                ("average_completion_rate", models.FloatField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user",)},
            },
        ),
    ]
