# Generated by Django 4.2 on 2025-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_surveys", models.IntegerField(default=0)),
                ("total_responses", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("active_subscriptions", models.IntegerField(default=0)),
                (
                    "monthly_growth",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Dashboard metrics",
                "db_table": "dashboard_metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("survey_responses", "Survey Responses"),
                            ("survey_analytics", "Survey Analytics"),
                            ("user_data", "User Data"),
                            ("payment_data", "Payment Data"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                ("filters", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "export_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_responses", models.IntegerField(default=0)),
                (
                    "skip_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("average_time_spent", models.IntegerField(default=0)),
                ("response_distribution", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Question analytics",
                "db_table": "question_analytics",
            },
        ),
        migrations.CreateModel(
            name="ResponseAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_spent", models.IntegerField(default=0)),
                ("is_complete", models.BooleanField(default=True)),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Response analytics",
                "db_table": "response_analytics",
            },
        ),
        migrations.CreateModel(
            name="SurveyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("total_responses", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("average_completion_time", models.IntegerField(default=0)),
                (
                    "bounce_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Survey analytics",
                "db_table": "survey_analytics",
            },
        ),
        migrations.CreateModel(
            name="SurveySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("respondent_id", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("time_spent", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "db_table": "survey_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("survey_created", "Survey Created"),
                            ("survey_edited", "Survey Edited"),
                            ("survey_published", "Survey Published"),
                            ("survey_deleted", "Survey Deleted"),
                            ("response_submitted", "Response Submitted"),
                            ("template_used", "Template Used"),
                            ("payment_made", "Payment Made"),
                            ("subscription_changed", "Subscription Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "User activities",
                "db_table": "user_activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
