# Generated by Django 4.2 on 2025-08-12 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="surveys.survey",
            ),
        ),
        migrations.AddField(
            model_name="surveyanalytics",
            name="survey",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="surveys.survey",
            ),
        ),
        migrations.AddField(
            model_name="responseanalytics",
            name="response",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="surveys.response",
            ),
        ),
        migrations.AddField(
            model_name="questionanalytics",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="surveys.question",
            ),
        ),
        migrations.AddField(
            model_name="exportlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="export_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboardmetrics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardmetrics",
            unique_together={("user", "date")},
        ),
    ]
