# Generated by Django 4.2 on 2025-08-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("customer-feedback", "Customer Feedback"),
                            ("employee", "Employee"),
                            ("academic", "Academic"),
                            ("health", "Health"),
                            ("event", "Event"),
                            ("community", "Community"),
                            ("market-research", "Market Research"),
                            ("product-feedback", "Product Feedback"),
                            ("service-evaluation", "Service Evaluation"),
                            ("user-experience", "User Experience"),
                            ("advanced-survey", "Advanced Survey"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("webinar", "Webinar"),
                            ("meetup", "Meetup"),
                            ("training", "Training"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("survey", "Survey"), ("event", "Event")],
                        max_length=20,
                    ),
                ),
                ("template_data", models.JSONField()),
                ("questions", models.JSONField(default=list)),
                ("estimated_time", models.CharField(blank=True, max_length=50)),
                ("response_count", models.IntegerField(default=0)),
                ("target_audience", models.TextField(blank=True)),
                ("use_cases", models.JSONField(default=list)),
                ("insights", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_general_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
